pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = '${WORKSPACE}/deploy/ansible.cfg'
    }

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    // string(name: 'webserver', defaultValue: false,  description: 'Ansible tag to run against webserver only')
    }

  stages {

    stage("Initial cleanup") {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }


    stage('SCM Checkout') {
      steps {
        script {
          git branch: 'main', url: 'https://github.com/Hack-Light/ansible-config-mgt'
        }
      }
    }

    stage('Prepare Ansible For Execution') {
      steps {
        sh 'echo ${WORKSPACE}'
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
      }
    }

    stage('Execute Ansible') {
      steps {
        script {
          ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}.txt', playbook: 'playbooks/site.yml'
        }
      }
    }

    stage('Clean Workspace after build'){
      steps{
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }
  }
}
