---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
    - name: create directory
      file:
        path: ~/ansible-test
        state: directory
- name: Update lb server
  hosts: lb
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: update apt repo
      apt:
        update_cache: yes
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
    - name: Run some command
      command: 'echo "I load balance everything in the whole wide world"'